Blosc/bloscpack

.travis.yml

http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

accelerate travis builds with docker

---

README.rst
test_cmdline/cram_strap.sh

Release 0.7.2

---

requirements.txt
setup.py

This in conjunction with https://github.com/Blosc/python-blosc/issues/114 should make all well again.

Unpinned blosc from 1.2.7

---

README.rst
bloscpack/abstract_io.py

Improved the computation of the chunksize when it is not divisible by typesize

---

.gitignore
README.rst
test/test_append.py
test/test_file_io.py
test/test_headers.py
test_cmdline/test_append.cram
test_cmdline/test_codec.cram
test_cmdline/test_help.cram
test_cmdline/test_info.cram
test_cmdline/test_metadata.cram
test_cmdline/test_verbose_debug.cram
test_requirements.txt

Addresses #55
@esc Travis is now happy. 
https://travis-ci.org/oogali/bloscpack

Fixed failing tests

---

bloscpack/args.py
test/test_args.py

fixes #11 cc @FrancescAlted @FrancescElies

allow Pythonic None as checksum

---

test/test_headers.py

fixes #62 and splits test in three tests. What do you think?

fixes test & splits test in 3 tests

---

conda.recipe/meta.yaml

upgrade to 0.11.0 and unpinn blosc

---

README.rst
bloscpack/args.py

slowing moving towards a Python-API

documenting args objects

---

LICENSE
MANIFEST.in

Add license file and include in sdist packages

---

.travis.yml
README.rst
bloscpack/append.py
bloscpack/file_io.py
bloscpack/testutil.py
bloscpack/util.py
setup.py
test_requirements.txt

Remove 2.6 support

---

README.rst

adding a mention of the Blosc Code of Conduct

---

bloscpack/__init__.py
bloscpack/file_io.py
test/test_file_io.py

Some more utilities to pack and unpack from and to bytes. Pretty basic stuff, surprised it wasn't implemented yet.

Feature: bytes bytes

---

test/test_append.py

As of blosc 1.6.1 this test was failing. Basically, the linspace data
used in the test is no longer compressible by blosc when not using the
shuffle, because the internal threshold has probaby changed. We
circumvent this issue, by using np.zeors which is certainly
compressible, with and without shuffle. The code is now a little bit
irky so more comments were added.

Fix: test_append_mix_shuffle

---

LICENSE
README.rst

update LICENSE file and license in README to 3-clause BSD

---

.github/workflows/testbloscpack.yml
.travis.yml
bloscpack/file_io.py
bloscpack/memory_io.py
bloscpack/numpy_io.py
bloscpack/testutil.py
setup.py
test.sh
test/test_append.py
test/test_args.py
test/test_checksums.py
test/test_cli.py
test/test_file_io.py
test/test_headers.py
test/test_log.py
test/test_memory_io.py
test/test_metacodecs.py
test/test_numpy_io.py
test/test_pretty.py
test/test_serializers.py
test_requirements.txt

The patch from #99
Any plans to make a new release? 0.16 is broken with current numpy.

migrate from nose to pytest

---

bloscpack/file_io.py
bloscpack/memory_io.py
bloscpack/numpy_io.py
bloscpack/testutil.py

PR #103 introduced a number of bugs, this fixes some of them.

revert refactoring

---

test/test_numpy_io.py

The PR #103 introduced some failed refactorings regarding testing of
Numpy arrays. This fixes that.

fix failed refactoring

---

.github/workflows/testbloscpack.yml
README.rst
setup.py

update supported Python versions

---

README.rst

adding gha badge to README

---

README.rst
test.sh
test/test_file_io.py

remove references to nosetest in README

---

pytest.ini

add missing pytest.ini
